# Generated by Django 5.1.15 on 2026-10-03 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(db_index=True, max_length=32, unique=True)),
                ('age', models.PositiveIntegerField(default=28)),
                ('gender', models.CharField(default='Male', max_length=20)),
                ('diagnosis', models.CharField(default='Severe Persistent Asthma', max_length=255)),
                ('status', models.CharField(choices=[('STABLE', 'Stable'), ('NEEDS REVIEW', 'Needs Review'), ('CRITICAL', 'Critical'), ('ALERT', 'Alert')], db_index=True, default='STABLE', max_length=30)),
                ('adherence_rate', models.FloatField(default=94.0)),
                ('room_bed', models.CharField(blank=True, default='', max_length=64)),
                ('prescribed_medication', models.CharField(default='Budesonide 0.5mg / 2ml', max_length=255)),
                ('daily_sessions_target', models.PositiveIntegerField(default=2)),
                ('daily_sessions_completed', models.PositiveIntegerField(default=1)),
                ('emergency_contact_name', models.CharField(default='Elena Mercer', max_length=255)),
                ('emergency_contact_phone', models.CharField(default='+1 (555) 019-2831', max_length=50)),
                ('emergency_contact_relationship', models.CharField(default='Spouse / Primary Caregiver', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_caregiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caregiver_patients', to=settings.AUTH_USER_MODEL)),
                ('assigned_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_patients', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Patient Profile',
                'verbose_name_plural': 'Patient Profiles',
                'db_table': 'smartneb_patient_profiles',
                'ordering': ['patient_id'],
            },
        ),
    ]
