# Generated by Django 5.1.15 on 2026-10-03 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('WARNING', 'Warning'), ('INFO', 'Info')], db_index=True, default='INFO', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_resolved', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='patients.patientprofile')),
            ],
            options={
                'verbose_name': 'Alert',
                'verbose_name_plural': 'Alerts',
                'db_table': 'smartneb_alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SOSEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(default=37.7749)),
                ('longitude', models.FloatField(default=-122.4194)),
                ('location_address', models.CharField(default='104 Health Ave, San Francisco, CA', max_length=255)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DISPATCHED', 'Dispatched'), ('RESOLVED', 'Resolved')], db_index=True, default='ACTIVE', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sos_events', to='patients.patientprofile')),
                ('triggered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggered_sos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SOS Event',
                'verbose_name_plural': 'SOS Events',
                'db_table': 'smartneb_sos_events',
                'ordering': ['-triggered_at'],
            },
        ),
    ]
