/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        surface: "#F8FAFC",
        "surface-card": "#FFFFFF",
        "surface-dim": "#F1F5F9",
        "surface-bright": "#FFFFFF",
        "surface-container-lowest": "#FFFFFF",
        "surface-container-low": "#F1F5F9",
        "surface-container": "#E2E8F0",
        "surface-container-high": "#CBD5E1",
        "surface-container-highest": "#94A3B8",
        background: "#F8FAFC",
        "on-background": "#0F172A",
        "on-surface": "#0F172A",
        "on-surface-variant": "#64748B",
        "border-subtle": "#E2E8F0",
        outline: "#CBD5E1",
        "outline-variant": "#E2E8F0",
        
        primary: "#0D9488",
        "primary-hover": "#0F766E",
        "primary-container": "#CCFBF1",
        "on-primary": "#FFFFFF",
        "on-primary-container": "#115E59",
        "primary-fixed": "#89F5E7",
        "primary-fixed-dim": "#6BD8CB",
        "on-primary-fixed": "#00201D",
        "on-primary-fixed-variant": "#005049",
        
        secondary: "#0284C7",
        "secondary-container": "#E0F2FE",
        "on-secondary": "#FFFFFF",
        "on-secondary-container": "#0369A1",
        "secondary-fixed": "#CCE5FF",
        "secondary-fixed-dim": "#93CCFF",
        "on-secondary-fixed": "#001D31",
        "on-secondary-fixed-variant": "#004B73",
        
        tertiary: "#4648D4",
        "tertiary-container": "#E0E7FF",
        "on-tertiary": "#FFFFFF",
        "on-tertiary-container": "#3730A3",
        "tertiary-fixed": "#E1E0FF",
        "tertiary-fixed-dim": "#C0C1FF",
        "on-tertiary-fixed": "#07006C",
        "on-tertiary-fixed-variant": "#2F2EBE",
        
        error: "#EF4444",
        "error-container": "#FEE2E2",
        "on-error": "#FFFFFF",
        "on-error-container": "#991B1B",
        
        success: "#10B981",
        warning: "#F59E0B",
        emerald: "#10B981",
        "warm-amber": "#F59E0B",
        "coral-red": "#EF4444",
      },
      spacing: {
        gutter: "1rem",
        margin: "1.5rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2rem",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        body: ["Inter", "DM Sans", "sans-serif"],
        headline: ["Inter", "Space Grotesk", "sans-serif"],
        "headline-md": ["Space Grotesk", "sans-serif"],
        "headline-sm": ["Space Grotesk", "sans-serif"],
        "body-md": ["DM Sans", "Inter", "sans-serif"],
        "body-sm": ["DM Sans", "Inter", "sans-serif"],
        "label-lg": ["DM Sans", "Inter", "sans-serif"],
        "label-md": ["DM Sans", "Inter", "sans-serif"],
        "label-sm": ["DM Sans", "Inter", "sans-serif"],
      },
      fontSize: {
        label: ["12px", { lineHeight: "16px", fontWeight: "500" }],
        body: ["14px", { lineHeight: "20px", fontWeight: "400" }],
        title: ["18px", { lineHeight: "24px", fontWeight: "600" }],
        headline: ["24px", { lineHeight: "32px", fontWeight: "600" }],
        display: ["32px", { lineHeight: "40px", fontWeight: "700" }],
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        sm: "0.25rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      }
    },
  },
  plugins: [],
}
