# Generated by Django 5.1.15 on 2026-10-03 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('model_name', models.CharField(default='SmartNeb Pocket-01', max_length=128)),
                ('status', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('SYNCING', 'Syncing'), ('MAINTENANCE', 'Maintenance'), ('IN USE', 'In Use')], db_index=True, default='ONLINE', max_length=32)),
                ('battery_level', models.PositiveIntegerField(default=87)),
                ('signal_rssi', models.IntegerField(default=-62)),
                ('mesh_status', models.CharField(default='Connected (Node 04)', max_length=128)),
                ('firmware_version', models.CharField(default='v2.4.1-rc3', max_length=64)),
                ('hardware_version', models.CharField(default='v1.2', max_length=64)),
                ('medication_chamber_level', models.PositiveIntegerField(default=78)),
                ('last_sync', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='patients.patientprofile')),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
                'db_table': 'smartneb_devices',
                'ordering': ['device_id'],
            },
        ),
    ]
