# Generated by Django 5.1.15 on 2026-10-03 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TherapyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(default='Budesonide 0.5mg / 2ml', max_length=255)),
                ('dosage_ml', models.FloatField(default=2.0)),
                ('target_flow_rate', models.FloatField(default=0.28)),
                ('duration_seconds', models.PositiveIntegerField(default=600)),
                ('daily_frequency', models.PositiveIntegerField(default=2)),
                ('instructions', models.TextField(blank=True, default='Sit upright. Inhale slowly and deeply through the mouthpiece. Exhale normally.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='therapy_plans', to='patients.patientprofile')),
                ('prescribed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescribed_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Therapy Plan',
                'verbose_name_plural': 'Therapy Plans',
                'db_table': 'smartneb_therapy_plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TherapySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('IDLE', 'Idle'), ('RUNNING', 'Running'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='IDLE', max_length=20)),
                ('total_duration_seconds', models.PositiveIntegerField(default=600)),
                ('elapsed_seconds', models.PositiveIntegerField(default=0)),
                ('delivered_dosage_ml', models.FloatField(default=0.0)),
                ('average_flow_rate', models.FloatField(default=0.28)),
                ('average_spo2', models.FloatField(default=98.0)),
                ('average_pulse', models.PositiveIntegerField(default=74)),
                ('notes', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='devices.device')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='therapy_sessions', to='patients.patientprofile')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='therapy.therapyplan')),
            ],
            options={
                'verbose_name': 'Therapy Session',
                'verbose_name_plural': 'Therapy Sessions',
                'db_table': 'smartneb_therapy_sessions',
                'ordering': ['-created_at'],
            },
        ),
    ]
