# Generated by Django 5.1.15 on 2026-10-03 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Telemetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spo2', models.FloatField(default=98.0)),
                ('pulse', models.PositiveIntegerField(default=74)),
                ('flow_rate', models.FloatField(default=0.28)),
                ('respiratory_rate', models.PositiveIntegerField(default=16)),
                ('inhalation_exhalation_ratio', models.CharField(default='1:2', max_length=20)),
                ('airway_pressure', models.FloatField(default=14.2)),
                ('battery', models.PositiveIntegerField(default=87)),
                ('recorded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telemetry_records', to='devices.device')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_records', to='patients.patientprofile')),
            ],
            options={
                'verbose_name': 'Telemetry Record',
                'verbose_name_plural': 'Telemetry Records',
                'db_table': 'smartneb_telemetry',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['patient', '-recorded_at'], name='smartneb_te_patient_2e7655_idx')],
            },
        ),
    ]
