# Generated by Django 5.1.15 on 2026-10-03 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=128)),
                ('entity_type', models.CharField(blank=True, default='', max_length=64)),
                ('entity_id', models.CharField(blank=True, default='', max_length=64)),
                ('details', models.TextField(blank=True, default='')),
                ('status', models.CharField(default='SUCCESS', max_length=32)),
                ('ip_address', models.CharField(blank=True, default='', max_length=45)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'smartneb_audit_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
